# Generated by Django 4.2.20 on 2025-05-04 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50, unique=True, verbose_name='Логин студента')),
                ('year', models.CharField(max_length=4, verbose_name='Год')),
                ('course', models.CharField(max_length=10, verbose_name='Курс')),
                ('group', models.CharField(max_length=50, verbose_name='Группа')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО студента')),
                ('title', models.CharField(max_length=255, verbose_name='Тема работы')),
                ('adviser_name', models.CharField(max_length=200, verbose_name='ФИО руководителя')),
                ('adviser_status', models.CharField(max_length=100, verbose_name='Звание руководителя')),
                ('department', models.CharField(max_length=100, verbose_name='Кафедра')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('index', 'Индексный файл'), ('preview', 'Предварительный документ'), ('final', 'Финальный документ')], max_length=20, verbose_name='Тип документа')),
                ('file', models.FileField(upload_to='students/%Y/%m/%d/', verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='webd_core.student')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
