# Generated by Django 4.2.20 on 2025-05-09 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webd_core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='full_name',
        ),
    ]
