# Generated by Django 4.2.20 on 2025-05-09 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webd_core', '0002_rename_name_student_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='adviser_name',
            field=models.CharField(max_length=200, null=True, verbose_name='ФИО руководителя'),
        ),
        migrations.AlterField(
            model_name='student',
            name='adviser_status',
            field=models.CharField(max_length=100, null=True, verbose_name='Звание руководителя'),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(max_length=100, null=True, verbose_name='Кафедра'),
        ),
        migrations.AlterField(
            model_name='student',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name='Тема работы'),
        ),
    ]
