# Generated by Django 4.2.20 on 2025-05-09 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webd_core', '0004_alter_student_adviser_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='course',
            new_name='courses',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='group',
            new_name='groups',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='year',
            new_name='study_year',
        ),
    ]
